version: "3.8"
services:
  nodeserver:
    restart: always
    build:
      context: ./server
    ports:
      - "5823:5823"
    volumes:
      - ./server:/usr/src/app
      - "./:/src"
      - "/usr/src/app/node_modules" # TODO check if / ís needed to add at the end
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    links:
      - db

  client:
    restart: always
    build:
      context: ./client
    ports:
      - "3284:3284"
    volumes:
      - ./client:/usr/src/client
      - "/usr/src/client/node_modules" # TODO check if / ís needed to add at the end
    command: npm run dev

  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "6451:80"

  db:
    container_name: jrm_database
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    # ports:
    #   - "5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  db:
    driver: local
