
FROM node:alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci --loglevel warn
RUN npm install pm2 -g

COPY . .

ENV NODE_ENV=production

RUN npm run build

EXPOSE 5823

CMD ["pm2-runtime", "start", "./dist/index.js", "--name", "my-app"]

