
FROM node:alpine

ARG DIR=/usr/src/app/

WORKDIR $DIR

COPY package*.json $DIR

RUN npm ci --loglevel warn
RUN npm install pm2 -g

COPY . $DIR

COPY . .

ENV NODE_ENV=production

RUN npm run build
COPY . $DIR

EXPOSE 5823

CMD ["pm2-runtime", "start", "./dist/index.js", "--name", "my-app"]

