# File: .github/workflows/workflow.yml

on: push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: "Checkout Github Action"
        uses: actions/checkout@master

      - name: Setup Node 18.13.0
        uses: actions/setup-node@v1
        with:
          node-version: "18.13.0"
      - name: "npm install, build, and test"
        run: |
          npm install
          npm run build --if-present
        working-directory: server

      - name: "Run Azure webapp deploy action using publish profile credentials"
        uses: azure/webapps-deploy@v2
        with:
          app-name: as25-api
          publish-profile: ${{ secrets.AZUREWEBAPPPUBLISHPROFILE }}
          package: server
